.gitignore
src/index.js
test/test.js

As suggested in #1 with emitting only a single token for `yield from`

add support for `yield` and `yield from` (single-token)

---

src/index.js
test/test.js

Discovered when using decaffeinate to translate a class that extended event emitter. 
Example problems:
```
@on('EVENT', handle_fn)
this.on('EVENT', handle_fn));
```
Or
```
@on('EVENT')
this.on(('EVENT'));

fix: @on() is a function call not a bool followed by parens

---

src/index.js
test/test.js

Closes https://github.com/decaffeinate/decaffeinate-parser/issues/14.
Closes https://github.com/decaffeinate/decaffeinate/issues/229.
Closes https://github.com/decaffeinate/decaffeinate/issues/435.
The code that builds interpolation tokens had a case where it handled
intermediate string fragments in the template string, but sometimes it would
falsely identify a double-quoted string inside an interpolation as one of these
string fragments. Fortunately, we already track a boolean for whether we're
inside an interpolation or not, so we can just add that boolean to the check.
This issue ended up causing the range of the string template to be interpreted
incorrectly (the end would be too soon), which caused an infinite loop in
decaffeinate-parser when it searched backward from the end until …

fix: properly handle double-quoted strings within string interpolations

---

src/index.js
test/test.js

Closes https://github.com/decaffeinate/decaffeinate/issues/437.
If we see a DOT token, then the next token shouldn't be treated as a keyword
because it should instead be seen as a property access. This was already handled
in the code, but it's even true when there's a newline in between the dot and
the keyword. So, when computing the previous token, we want to skip any NEWLINE
tokens we see, and check if the next earlier one is a DOT (or PROTO or AT).

fix: allow newlines when looking for identifiers after DOT tokens

---

src/utils/tripleQuotedStringSourceLocations.js
test/test.js

Fixes decaffeinate/decaffeinate#555
This is similar to #54, but triple-quoted strings end up using a different code
path, so we need to handle those as well.

fix: avoid infinite loop on incomplete interpolated triple-quoted strings

---

README.md
src/index.js
src/utils/tripleQuotedStringSourceLocations.js
test/test.js

Progress toward https://github.com/decaffeinate/decaffeinate/issues/557
Now that https://github.com/decaffeinate/decaffeinate/pull/553 has landed, we
can assume that any code passed through decaffeinate only has LF line endings,
which simplifies some code, particularly when dealing with triple-quoted
strings.

refactor: remove code handling \r characters

---

src/SourceTokenList.js
src/SourceTokenListIndex.js
src/coffee-lex.js.flow
src/index.js
src/utils/tripleQuotedStringSourceLocations.js
test/test.js
test/utils/tripleQuotedStringSourceLocations_test.js

Progress toward https://github.com/decaffeinate/decaffeinate/issues/557
After this change, all four types of strings are treated similarly: they're
generated initially with `[type]_START`, `STRING_CONTENT`, and `[type]_END`,
potentially with interpolations, then later code might process them further. The
`tripleQuotedStringSourceLocations` function behaves the same and was changed to
recognize the new format and output the same format as before.
I intentionally split `STRING_START` and `STRING_END` into four types, since
later code will want to look at the actual type to know how to compute the
whitespace to strip.
BREAKING CHANGE: The TDSTRING, TSSTRING, STRING_START, and STRING_END tokens
have been removed. Instead, strings always have a specific start and end token
for their type of …

refactor: change herestrings to share initial lexing code with normal strings

---

src/coffee-lex.js.flow
src/index.js
test/test.js

Progress toward https://github.com/decaffeinate/decaffeinate/issues/557
I was originally planning to make normal regexes use the same strategy, but it
looks like regex lexing is tricky, probably because the `/` character could also
mean division. So we only use the `[type]_START`, `STRING_CONTENT`, `[type]_END`
approach for heregexes and strings.
BREAKING CHANGE: The HEREGEXP token type has been replaced with HEREGEXP_START
and HEREGEXP_END.

feat: add basic lexing for string interpolations in heregexes

---

src/index.js
src/utils/calculateHeregexpPadding.js
test/test.js
test/utils/calculateHeregexpPadding_test.js
test/utils/calculateNormalStringPadding_test.js
test/utils/verifyStringMatchesCoffeeScript.js

Progress toward these issues:
https://github.com/decaffeinate/decaffeinate/issues/557
https://github.com/decaffeinate/decaffeinate/issues/341
Heregexes have relatively simple rules for whitespace padding, but there is some
complexity because I needed to handle comments and escaped spaces.
This change also refactors the test code to be shared.

feat: calculate padding for heregexes

---

src/utils/PaddingTracker.js
src/utils/calculateTripleQuotedStringPadding.js
test/utils/calculateTripleQuotedStringPadding_test.js
test/utils/verifyStringMatchesCoffeeScript.js

Progress toward these issues:
https://github.com/decaffeinate/decaffeinate/issues/557
https://github.com/decaffeinate/decaffeinate/issues/556
There are a number of edge cases in dealing with herestring padding that are
handled in decaffeinate-parser but weren't properly handled in coffee-lex, so
this change ports those changes over using the PaddingTracker approach, which
also means that the padding strategy works for interpolations.

fix: rework herestring padding to better agree with CoffeeScript

---

src/SourceTokenList.js
test/test.js

Progress toward these issues:
https://github.com/decaffeinate/decaffeinate/issues/557
https://github.com/decaffeinate/decaffeinate/issues/341
This should let decaffeinate-parser determine heregex locations without having
to jump through additional hoops.

fix: include heregex tokens when determining interpolated string ranges

---

package.json

This doesn't really affect anything; I've never really used it. This does not remove semantic-release.

chore: remove conventional changelog

---

package.json
test/mocha.opts
test/test.ts
test/utils/PaddingTracker_test.ts
test/utils/calculateHeregexpPadding_test.ts
test/utils/calculateNormalStringPadding_test.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

* Run the typecheck script as `tsc -p . --noEmit` to avoid writing build
artifacts, since that command is just for typechecking. This means that we
don't need to worry about mocha picking up generated JS files when it discovers
tests.
* Change the mocha build to use ts-node as a compiler, which is nice because it
avoids the usual build step and makes it so WebStorm can debug the source ts
files directly.
* Change the test syntax back to normal mocha `describe`/`it` syntax so that
WebStorm can parse the test files to allow you to run individual tests.
* Fix some accidental imports of `verifyStringMatchesCoffeeScript.js`.
The conversion back to normal mocha syntax was mostly done by running this
highly-unscientific sed command, then cleaning up the collateral damage:
```
sed -i '' "s/@suite …
```

chore: update TypeScript test setup to work better in WebStorm

---

src/SourceToken.ts
src/SourceTokenList.ts
test/test.ts

Progress toward https://github.com/decaffeinate/decaffeinate/issues/612
SourceTokenList usage is the main (maybe only) case where decaffeinate has
behavior that can be O(n^2) in the size of the source code, so this commit fixes
some linear scans and extends the API to allow calling code to avoid linear
scans:
* `indexOfTokenContainingSourceIndex` and friends were all doing a linear scan
through all tokens to find one at the right index. Instead, I precompute a
table mapping source index to token index and just do a fast lookup in that
table. (I also considered binary search, but the table approach is simpler and
a little faster and I think the memory usage isn't a concern).
* `indexOfTokenMatchingPredicate` and `lastIndexOfTokenMatchingPredicate`
allowed you to optionally specify a start …

feat: improve performance in SourceTokenList

---

declarations/decaffeinate-coffeescript.d.ts
package.json
script/build
tsconfig.json

Updating to decaffeinate-coffeescript@1.10.0-patch6 means we get the type information from the included `.d.ts` files, so we can ditch the simplified one in `declarations`.

chore(package): update dependencies

---

src/SourceTokenList.ts
src/SourceType.ts
src/index.ts
src/utils/PaddingTracker.ts
src/utils/calculateHeregexpPadding.ts
src/utils/calculateNormalStringPadding.ts
src/utils/calculateTripleQuotedStringPadding.ts
test/test.ts
test/utils/PaddingTracker_test.ts
test/utils/calculateTripleQuotedStringPadding_test.ts
test/utils/verifyStringMatchesCoffeeScript.ts

Because both decaffeinate-parser and decaffeinate depend on coffee-lex, it's possible for their versions to be mismatched such that npm will install multiple copies of coffee-lex. This results in problems because the tokens coffee-lex generates have a source type that is an instance of the `SourceType` class, meaning that the same source type in different copies will not be equal to each other, making checking that a token is of a particular type, e.g. `CALL_START`, impossible if the token was created using a different version of coffee-lex than the one used to check the type.
BREAKING CHANGE: To fix this I've changed the `SourceType` class to be an `enum`, so its values will just be explicit numbers that will compare correctly across versions of coffee-lex. Because this changes the API …

fix: ensure multiple copies of coffee-lex can coexist

---

src/SourceLocation.ts
src/SourceToken.ts
src/SourceTokenList.ts
src/SourceTokenListIndex.ts
src/utils/BufferedStream.ts
src/utils/PaddingTracker.ts

Due to TypeScript's lack of an `internal` access modifier, I am using subscripts with strings to access private members from within related classes. Any class member not intended to be reassigned gets `readonly`.

fix: restrict access to properties/methods intended to be private/readonly

---

src/index.ts
test/test.ts

Previously, this would be lexed as a `DOT` followed by a `NUMBER`. The regular expression we use to match actually does work with numbers with leading dots, but we were consuming `.` by itself with higher precedence. To fix it, we just move the `NUMBER` match up ahead of the `DOT`.

fix: lex a number with a leading dot as one token

---

package.json
src/SourceType.ts
src/index.ts
test/test.ts

Progress toward https://github.com/decaffeinate/decaffeinate/issues/702
This was already mostly done, but had two issues:
* Since we didn't have token types for increment and decrement, there wasn't a
way to check if a regex is predeced by increment or decrement. To fix, I split
those out into their own source types.
* Regexes with flags were having the flags lexed as an identifier. To fix, I
consume any flags immediately following a regex and include that with the
token. This fixes the check for a regex immediately followed by another regex.
BREAKING CHANGE: Increment and decrement tokens now have source type `INCREMENT`
and `DECREMENT` rather than `OPERATOR`. Also, regular expression tokens no
longer incorrectly have an identifier token for their flags.

fix: properly identify when regex-like code should be division

---

src/index.ts
test/test.ts

Previously we would use a keyword-specific token type, such as `BREAK` or `CONTINUE`, for tokens in an object property position. This commit ensures that, if the keyword is followed by a colon, it will be treated as an `IDENTIFIER` and not as a keyword token.
Closes decaffeinate/decaffeinate#713

fix: always use `IDENTIFIER` for object key tokens

---

src/index.ts
test/test.ts

The regular expression matched without an anchor, so any keyword followed by a colon anywhere on the same line would count as an identifier.
Refs decaffeinate/decaffeinate#718

fix: ensure keywords are not identifiers when appropriate

---

src/SourceType.ts
src/index.ts
test/test.ts

BREAKING CHANGE: Previously, `new` was treated as an `IDENTIFIER`. Now, it is treated as its own token, `NEW`, when used in the right context.

fix: treat `new` in the right context as a distinct token

---

src/utils/calculateTripleQuotedStringPadding.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

Fixes https://github.com/decaffeinate/decaffeinate/issues/927
Our test for "is this a whitespace-only line" didn't quite work, since it
returned true for the end of a fragment that was followed by an interpolation.
Now, we limit that test to cases where the line we have is actually the full
line from the source code, i.e. intermediate lines in fragments and the last
line of the last fragment.

fix: properly calculate herestring indentation before interpolations

---

src/utils/calculateNormalStringPadding.ts
src/utils/calculateTripleQuotedStringPadding.ts
src/utils/isNewlineEscaped.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

Fixes https://github.com/decaffeinate/decaffeinate/issues/1025
The rules for triple quoted and regular multiline strings are the same (it
seems), so we can mostly just refactor it into a shared function used by both.

fix: remove escaped newlines from triple-quoted strings

---

src/utils/calculateTripleQuotedStringPadding.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

In triple-quoted strings, we need to remove all whitespace following an escaped
newline, including any newline characters.

fix: also remove following whitespace after escaped newlines

---

src/utils/calculateNormalStringPadding.ts
test/utils/calculateNormalStringPadding_test.ts
test/utils/verifyStringMatchesCoffeeScript.ts

This is a refinement of some previous changes around handling escaped whitespace
characters. It looks like if you escape a space character between two lines, all
following whitespace characters are included.

fix: don't treat escaped spaces or tabs as whitespace in normal strings

---

src/utils/calculateTripleQuotedStringPadding.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

CoffeeScript always removes escaped newlines and all following whitespace before
doing later processing in the herestring case, so we need to emulate that
behavior when removing the initial and final line of a herestring.

fix: properly account for escaped newlines when trimming the string start/end

---

src/utils/calculateTripleQuotedStringPadding.ts
test/utils/calculateTripleQuotedStringPadding_test.ts

When splitting lines, we now ignore all whitespace after an escaped newline,
including later that occur before non-whitespace characters.

fix: further replicate the CoffeeScript behavior on line trimming

---

src/index.ts
test/test.ts

I mixed up my brackets and braces when reading the CoffeeScript code and
accidentally ignored after braces.

fix: skip CSX parsing when immediately following an rbracket

---

.travis.yml

Test in the latest (v11) and all currently supported LTS versions. Node v6 is supported until April 2019, so we can remove it after that.

test(ci): update node versions to test with

---

.eslintrc
package.json
src/SourceTokenList.ts
src/SourceTokenListIndex.ts
src/__tests__/test.ts
src/__tests__/utils/PaddingTracker_test.ts
src/__tests__/utils/calculateHeregexpPadding_test.ts
src/__tests__/utils/calculateNormalStringPadding_test.ts
src/__tests__/utils/calculateTripleQuotedStringPadding_test.ts
src/__tests__/utils/setupTests.ts
src/__tests__/utils/verifyStringMatchesCoffeeScript.ts
src/index.ts
src/utils/calculateHeregexpPadding.ts
src/utils/calculateNormalStringPadding.ts
src/utils/calculateTripleQuotedStringPadding.ts
src/utils/isNewlineEscaped.ts
yarn.lock

For some reason the `lint` script was not actually running on all the files. This fixes it by letting eslint itself handle the globbing rather than the shell.
This commit also upgrades everything, so some rules got updated in a way that changed the source code.

style(lint): fix eslint integration

---

src/SourceTokenList.ts

This was flagged by LGTM: https://lgtm.com/projects/g/decaffeinate/coffee-lex/snapshot/8c2297bca449499550201946a4f15c7dffd547f0/files/src/SourceTokenList.ts?sort=name&dir=ASC&mode=heatmap#x67e7ccb72f204d67:1
I believe this conditional was present because previous versions of TypeScript were not smart enough to infer that `i` would never be `null` at that position. At some point, TS got smart enough and we can remove the conditional.

refactor: remove unneeded conditional

---

.circleci/config.yml

Node v8.x is about to be EOL’d, and Node v13.x is now available. This drops the one and adds the other.

test(ci): update node versions to test

---

package.json

This is now automatic, and adding it to the config logs a warning:
```
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```

build(dev-deps): remove unnecessary `git add` from `lint-staged` config

---

.github/workflows/release.yml

Otherwise we don't have access to the `NPM_TOKEN` secret.

ci(release): run in the right environment

---

src/index.ts
src/lex.ts

Both decaffeinate and decaffeinate-parser were reaching into the package by importing e.g. `coffee-lex/dist/SourceToken`. This is no longer allowed because I defined the `exports` object in `package.json`. Additionally, since the `dist` only includes a bundled `index.(m)js`, this wouldn't work anyway.
This commit exports all the things that decaffeinate-parser and decaffeinate need.

fix(package): export all the things

---

src/SourceToken.ts
src/SourceTokenList.ts
src/SourceTokenListIndex.ts
src/__tests__/test.ts
src/__tests__/utils/calculateTripleQuotedStringPadding_test.ts
src/__tests__/utils/setupTests.ts
src/__tests__/utils/verifyStringMatchesCoffeeScript.ts
src/lex.ts
src/utils/PaddingTracker.ts
src/utils/assert.ts
src/utils/assertNever.ts
src/utils/calculateHeregexpPadding.ts
src/utils/calculateNormalStringPadding.ts
src/utils/calculateTripleQuotedStringPadding.ts

This preserves the source index at which the error happened.

feat(lex): use `CoffeeLexError` with source index

---

src/SourceTokenList.ts
src/__tests__/test.ts

I messed up the `assert` when I converted it from an `if/throw`.

fix(tokens): ensure `slice` works again

---

src/__tests__/test.ts
src/lex.ts

We were already checking for `RPAREN` tokens, but calls with parens have a `CALL_END` token instead of an `RPAREN` token.
Closes #2522

fix: lex non-CSX after a call properly
